/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.github.satya64.powerbi.api;

import io.github.satya64.powerbi.api.model.ODataResponse;
import okhttp3.mockwebserver.MockWebServer;
import org.junit.After;
import org.junit.Before;
import org.junit.Ignore;
import org.junit.Test;
import retrofit2.Retrofit;
import retrofit2.converter.jackson.JacksonConverterFactory;

import java.io.IOException;

import static org.junit.Assert.*;

@Ignore
public class PowerBiClientTest {

    private MockWebServer server = new MockWebServer();

    Retrofit retrofit = new Retrofit.Builder()
            .baseUrl("http://localhost/")
            .addConverterFactory(JacksonConverterFactory.create())
            .build();

    @Before
    public void init() throws IOException {
        server.start();
    }

    @After
    public void destroy() throws IOException {
        server.shutdown();
    }

    @Test public void testSomeLibraryMethod() {
        PowerBiClient classUnderTest = PowerBiClient.getInstance("abc.123.abc");
        assertNotNull("initialize should return 'true'", classUnderTest);
    }

}
