/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.github.satya64.powerbi.api;

import io.github.satya64.powerbi.api.model.ODataResponse;
import okhttp3.mockwebserver.MockWebServer;
import org.junit.After;
import org.junit.Before;
import org.junit.Ignore;
import org.junit.Test;
import retrofit2.Retrofit;
import retrofit2.converter.jackson.JacksonConverterFactory;

import java.io.IOException;

import static org.junit.Assert.*;

@Ignore
public class PowerBiClientTest {

    private MockWebServer server = new MockWebServer();

    Retrofit retrofit = new Retrofit.Builder()
            .baseUrl("http://localhost/")
            .addConverterFactory(JacksonConverterFactory.create())
            .build();

//    MockRetrofit mockRetrofit = new MockRetrofit.Builder(retrofit).networkBehavior(NetworkBehavior.create()).build();

    @Before
    public void init() throws IOException {
       // server.setDispatcher(new CustomMockDispatcher());
        server.start();
    }

    @After
    public void destroy() throws IOException {
        server.shutdown();
    }

    @Test public void testSomeLibraryMethod() {
        PowerBiClient classUnderTest = PowerBiClient.getInstance("eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6IllNRUxIVDBndmIwbXhvU0RvWWZvbWpxZmpZVSIsImtpZCI6IllNRUxIVDBndmIwbXhvU0RvWWZvbWpxZmpZVSJ9.eyJhdWQiOiJodHRwczovL2FuYWx5c2lzLndpbmRvd3MubmV0L3Bvd2VyYmkvYXBpIiwiaXNzIjoiaHR0cHM6Ly9zdHMud2luZG93cy5uZXQvNzY1M2FmNDgtOGQyNC00YzQzLWJiYWEtYjg1NDcxMzljMGY1LyIsImlhdCI6MTU4Njk1ODM0MiwibmJmIjoxNTg2OTU4MzQyLCJleHAiOjE1ODY5NjIyNDIsImFjY3QiOjAsImFjciI6IjEiLCJhaW8iOiI0MmRnWUVoeWtieWdhdmpPZm1YRTFlVld0YS9tZUdwbHlYazZ1bXcxL05xKy80L1JvU2tBIiwiYW1yIjpbInB3ZCJdLCJhcHBpZCI6Ijg1YmU2N2RhLTA4YWMtNGY0ZC04YjdmLTY4NWJkNWQ4NDFiMSIsImFwcGlkYWNyIjoiMCIsImdpdmVuX25hbWUiOiJzdmNfc2NvdXRfdGhiIiwiaW5fY29ycCI6InRydWUiLCJpcGFkZHIiOiIxOTguNzIuNzguMSIsIm5hbWUiOiJzdmNfc2NvdXRfdGhiIiwib2lkIjoiYWNjNGViNGItMzUwOS00MjA0LWI3Y2YtZTVmYmE2ZTQwY2FkIiwib25wcmVtX3NpZCI6IlMtMS01LTIxLTYwMjE2MjM1OC01Nzk4OTg0MS02ODIwMDMzMzAtMTgyNDk5IiwicHVpZCI6IjEwMDNCRkZEQTlCOTlBQkQiLCJzY3AiOiJDb250ZW50LkNyZWF0ZSBEYXNoYm9hcmQuUmVhZC5BbGwgRGFzaGJvYXJkLlJlYWRXcml0ZS5BbGwgRGF0YS5BbHRlcl9BbnkgRGF0YXNldC5SZWFkLkFsbCBEYXRhc2V0LlJlYWRXcml0ZS5BbGwgR3JvdXAuUmVhZCBHcm91cC5SZWFkLkFsbCBNZXRhZGF0YS5WaWV3X0FueSBSZXBvcnQuUmVhZC5BbGwgUmVwb3J0LlJlYWRXcml0ZS5BbGwgV29ya3NwYWNlLlJlYWQuQWxsIFdvcmtzcGFjZS5SZWFkV3JpdGUuQWxsIiwic3ViIjoiRTl5ZDVmb3QtekJoRzdxakRPcmdhdGRock1IaTU2YnRlWGp0MHNoZ2hwYyIsInRpZCI6Ijc2NTNhZjQ4LThkMjQtNGM0My1iYmFhLWI4NTQ3MTM5YzBmNSIsInVuaXF1ZV9uYW1lIjoic3ZjX3Njb3V0X3RoYkBtcmNvb3Blci5jb20iLCJ1cG4iOiJzdmNfc2NvdXRfdGhiQG1yY29vcGVyLmNvbSIsInV0aSI6ImxadnhiVTllTDAtOXRpam1idUNuQUEiLCJ2ZXIiOiIxLjAifQ.P3aFY9-f-B9JwQKxpG_Ny5Fklr3VhcmtOTM_0Pr0FyxKARXc4Ao_Rs_fSOf_yTW7ToHJ4CW5Omx6Wtwn6ujVYU2gkelYvWVIC0VDnTOPNsxb7l9vzz2Y9yMCOP2FEbQc97PK6bEqKo3d6AfVqKCq9tLwST24oURptIN2t4261faVPUG1_ReK5nVTuQUnSCXgUvkIciF4SvAhY4aL5zZI5UZI24PDl821hmceLHqATbdleF_SPWwXgr2R5E5vinxQE2jHaQtLrskv9VQSupgBpALvw8-O-IiMpDShdHaP3ac3hAA2SyP43YfCt1_DP90X2pdb6vENDCXYk1oVRCr2Gw");
        assertNotNull("initialize should return 'true'", classUnderTest);
    }

    public <T> ODataResponse<T> createResponse(T data){
        ODataResponse<T> res = new ODataResponse<>();
        res.setValue(data);
        return res;
    }


}
